### ISSUE TITLE
calendar undefined

### ISSUE THREAD

**Issue by faienz93** [ArrobeFr/jquery-calendar#4]
Hi 
i want print some events. This is my code: 
                             `
var calendar = $('#calendar').Calendar({
    locale: 'en',
    weekday: {
      timeline: {
        //   intervalMinutes: 30,
        fromHour: 8
      }
    },
    events: events,
    daynotes: daynotes
  }).init();

var result = calendar.getEvents();
 console.log(result);`

If i print the result I get error `
jquery-3.3.1.min.js:2 Uncaught TypeError: Cannot read property 'getEvents' of undefined`

**Comment by faienz93** [comment]
I resolve. I rewrite the code in this way: 
var calendar = $('#calendar').Calendar({
locale: 'en',
weekday: {
timeline: {
// intervalMinutes: 30,
fromHour: 8
}
},
events: events,
daynotes: daynotes
})

calendar.init();
var result = calendar.getEvents();
console.log(result);

**Comment by LeoVillaretArrobe** [comment]
Hi, the version 1.0.12 fix that. It was relased and published to npmjs.
