### ISSUE TITLE
Add event dinamically

### ISSUE THREAD

**Issue by faienz93** [ArrobeFr/jquery-calendar#6]
Sorry, can i ask an example on
- how to add an events dinamically, because the method setEvent in my code doesn't work
- set defaut color for category

thanks

**Comment by LeoVillaretArrobe** [comment]
[According to documentation](https://github.com/ArrobeFr/jquery-calendar#functions-list) :

- `setEvents` : **It replaces events !**
- `addEvents` : *It just adds events (it not replaces events)*

Finally you must always call again the `init` function (documentation : **It must be called after any modification to re-draw the calendar**)

To fix a category color, use this function `setEventCategoriesColors` and again call the `init` function.

Example to [add some events](https://cdn.rawgit.com/ArrobeFr/jquery-calendar/7b9d42aa/example/demo.html) is here and the [code is here](https://github.com/ArrobeFr/jquery-calendar/blob/master/example/demo.html)

Full example not tested but may work according to the [documentation](https://github.com/ArrobeFr/jquery-calendar#functions-list) :

```js
var now = moment();

// Requires a <div id="calendar"></div>
var calendar = $('#calendar').Calendar({});

// An event copied from the Simple example documentation (https://github.com/ArrobeFr/jquery-calendar#simple-example)
calendar.addEvents([
   { // An event on the current week on Wednesday from 10h to 12h
   start: now.startOf('week').isoWeekday(3).startOf('day').add(10, 'h').format('X'),
   end: now.startOf('week').isoWeekday(3).startOf('day').add(12, 'h').format('X'),
   title: 'An event title !',
   content: 'Hello World! <br>Foo Bar<p class="text-right">Wow this text is right aligned !</p>',
   category: 'A test category name'
   }
]);

// Turquoise color for the category of the event added
calendar.setEventCategoriesColors([
   {
      category: "A test category name",
      color: "#00838F"
   }
]);

calendar.init();
```
